lugares = ["seatle", "tókio", "pequim", "urubici", "floriano", "fernando de noronha"]
print("\nOrdem original da lista de lugares de interesse:")
print(lugares)
print("\nLista de lugares de interesse em ordem alfabética:")
print(sorted(lugares))
print("\nLista de lugares de interesse em ordem alfabética INVERSA:")
print(sorted(lugares, reverse = True))
print("\nLista de lugares de interesse ordenanda novamente na ordem original:")
print(lugares)
print("\nUso do método .reverse() para alterar ordem da lista:")
lugares.reverse()
print(lugares)
print("\nUso do método .reverse() para alterar ordem da lista:")
lugares.reverse()
print(lugares)
print("\nUso do método .sort() para ordenar lista em ordem alfabética:")
lugares.sort()
print(lugares)
print("\nUso do método .sort() para ordenar lista em ordem alfabética INVERSA:")
lugares.sort(reverse = True)
print(lugares)
