convidados = ["isacc newton", "albert einstein", "marie currie", "james watt"]
print("Olá Sr(a)" + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nEncontrei uma nova mesa de jantar com capacidade para mais três convidados.")
convidados.insert(0,"galileu galilei")
convidados.insert(3,"arquimedes")
convidados.append("nicolau copérnico")
print("\nOlá Sr(a) " + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[4].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[5].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[6].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
desconvidado = convidados.pop()
print("\nSr(a) " + desconvidado.title() + " Infelizmente houve um imprevisto e não poderei mais recebê-lo na recepção de terça-feira. Sinto Muito.")
desconvidado = convidados.pop()
print("\nSr(a) " + desconvidado.title() + " Infelizmente houve um imprevisto e não poderei mais recebê-lo na recepção de terça-feira. Sinto Muito.")
desconvidado = convidados.pop()
print("\nSr(a) " + desconvidado.title() + " Infelizmente houve um imprevisto e não poderei mais recebê-lo na recepção de terça-feira. Sinto Muito.")
desconvidado = convidados.pop()
print("\nSr(a) " + desconvidado.title() + " Infelizmente houve um imprevisto e não poderei mais recebê-lo na recepção de terça-feira. Sinto Muito.")
desconvidado = convidados.pop()
print("\nSr(a) " + desconvidado.title() + " Infelizmente houve um imprevisto e não poderei mais recebê-lo na recepção de terça-feira. Sinto Muito.")
print("\nSr " + convidados[0].title() + ", conto com a sua presença na recepção de terça-feira.")
print("\nSr " + convidados[1].title() + ", conto com a sua presença na recepção de terça-feira.")
