convidados = ["isacc newton", "albert einstein", "marie currie", "james watt"]
print("Olá Sr(a)" + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nO Sr." + convidados[3].title() + " não poderá comparecer a recepção!")
convidados.remove("james watt")
convidados.append("enrico fermi")
print("\nOlá Sr(a)" + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
