convidados = ["isacc newton", "albert einstein", "marie currie", "james watt"]
print("Olá Sr(a)" + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nO Sr." + convidados[3].title() + " não poderá comparecer a recepção!")
convidados.remove("james watt")
convidados.append("enrico fermi")
print("\nOlá Sr(a)" + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a)" + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nEncontrei uma nova mesa de jantar com capacidade para mais três convidados.")
convidados.insert(0,"galileu galilei")
convidados.insert(3,"arquimedes")
convidados.append("nicolau copérnico")
print("\nOlá Sr(a) " + convidados[0].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[1].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[2].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[3].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[4].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[5].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
print("\nOlá Sr(a) " + convidados[6].title() + ", tenho o prazer de convidá-lo para recepção em minha casa no dia 23/03/23 as 18:00 horas.")
num_conv = str(len(convidados))
print("\nConvites confirmados, a recepção na terça-feira terá a presença de " + num_conv + " convidados.")
